"""
gerrit_client.py
----------------
Gerrit REST API 클라이언트.

버전 자동 감지 → 기능(Capability) 레지스트리 조회 →
해당 버전에 맞는 최적 페이로드를 처음부터 올바르게 구성합니다.

새 Gerrit 버전 지원 추가 방법:
    GERRIT_VERSION_REGISTRY 에 한 줄만 추가하면 됩니다.

Gerrit REST API 문서:
    https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html
"""

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import quote

import requests
from requests.auth import HTTPBasicAuth, HTTPDigestAuth

logger = logging.getLogger(__name__)


# ==============================================================================
# Gerrit 버전별 기능(Capability) 레지스트리
# ==============================================================================
#
# ★ 새 Gerrit 버전 추가 시 이 리스트에 한 줄만 추가하세요.
#
# 형식: (최소 버전 튜플, 기능 딕셔너리)
# - 내림차순 정렬 필수 (높은 버전이 앞에)
# - 감지된 버전 >= 최소 버전인 첫 번째 항목 선택
#
# 기능 키:
#   tag             : SetReviewInput.tag 필드 (2.15+)
#   unresolved      : CommentInput.unresolved 필드 (3.0+)
#   inline_comments : SetReviewInput.comments 필드 (2.14+)
#   notify_none     : notify=NONE 값 (2.15+). False이면 notify 필드 생략
#   robot_comments  : robot_comments 필드 (2.14+)
#
GERRIT_VERSION_REGISTRY: list[tuple[tuple, dict]] = [
    # ★ 새 버전 추가 시 내림차순으로 한 줄 삽입
    #
    # 기능 키:
    #   labels          : SetReviewInput.labels 필드 (Code-Review 점수) 안정 지원
    #   tag             : SetReviewInput.tag 필드 (2.15+)
    #   unresolved      : CommentInput.unresolved 필드 (3.0+)
    #   inline_comments : SetReviewInput.comments 필드 (2.14+)
    #   notify_none     : notify=NONE 값 (2.15+)
    #   robot_comments  : robot_comments 필드 (2.14+)
    #
    # ── Gerrit 3.x ──────────────────────────────────────────────────────────
    ((3, 9), dict(labels=True, tag=True,  unresolved=True,  inline_comments=True,  notify_none=True,  robot_comments=True)),
    ((3, 5), dict(labels=True, tag=True,  unresolved=True,  inline_comments=True,  notify_none=True,  robot_comments=True)),
    ((3, 3), dict(labels=True, tag=True,  unresolved=True,  inline_comments=True,  notify_none=True,  robot_comments=True)),
    ((3, 0), dict(labels=True, tag=True,  unresolved=True,  inline_comments=True,  notify_none=True,  robot_comments=True)),
    # ── Gerrit 2.x ──────────────────────────────────────────────────────────
    ((2, 16), dict(labels=True, tag=True,  unresolved=False, inline_comments=True,  notify_none=True,  robot_comments=True)),
    ((2, 15), dict(labels=True, tag=True,  unresolved=False, inline_comments=True,  notify_none=True,  robot_comments=False)),
    ((2, 14), dict(labels=True, tag=False, unresolved=False, inline_comments=True,  notify_none=False, robot_comments=False)),
    ((2, 13), dict(labels=True, tag=False, unresolved=False, inline_comments=False, notify_none=False, robot_comments=False)),
    # ── 2.12 이하 / 버전 감지 실패 → 최소 기능 (message 만) ─────────────────
    ((0,  0), dict(labels=False, tag=False, unresolved=False, inline_comments=False, notify_none=False, robot_comments=False)),
]


# ==============================================================================
# 데이터 클래스
# ==============================================================================

@dataclass
class GerritCapabilities:
    """감지된 Gerrit 서버의 기능 집합"""
    version_str:     str   = "unknown"
    version_tuple:   tuple = (0, 0)
    labels:          bool  = False   # Code-Review 점수 레이블 안정 지원
    tag:             bool  = False
    unresolved:      bool  = False
    inline_comments: bool  = False
    notify_none:     bool  = False
    robot_comments:  bool  = False

    def summary(self) -> str:
        feats = [k for k in ("labels", "tag", "unresolved", "inline_comments",
                              "notify_none", "robot_comments") if getattr(self, k)]
        return (
            f"Gerrit {self.version_str} "
            f"(지원 기능: {', '.join(feats) if feats else '최소'})"
        )


@dataclass
class GerritChange:
    """Gerrit 변경사항 정보"""
    change_id:       str
    project:         str
    branch:          str
    subject:         str
    status:          str
    change_number:   int
    patchset_number: int
    owner:           str = ""
    created:         str = ""
    updated:         str = ""


@dataclass
class FileDiff:
    """파일별 diff 정보"""
    filename:       str
    old_path:       str = ""
    change_type:    str = "MODIFIED"
    lines_inserted: int = 0
    lines_deleted:  int = 0
    diff_content:   str = ""


@dataclass
class ReviewInput:
    """Gerrit 코드 리뷰 등록 입력"""
    message:  str  = ""
    labels:   dict = field(default_factory=dict)
    comments: dict = field(default_factory=dict)
    tag:      str  = "autogenerated:ai-reviewer"
    notify:   str  = "NONE"


# ==============================================================================
# 버전 유틸리티
# ==============================================================================

def parse_version(version_str: str) -> tuple:
    """
    버전 문자열 → 정수 튜플 변환

    "3.5.0.1"  → (3, 5, 0, 1)
    "2.16.28"  → (2, 16, 28)
    "3.9-rc1"  → (3, 9)
    ""         → (0, 0)
    """
    parts = re.findall(r"\d+", str(version_str))
    return tuple(int(p) for p in parts[:4]) if parts else (0, 0)


def detect_capabilities(version_tuple: tuple, version_str: str) -> GerritCapabilities:
    """
    버전 튜플을 GERRIT_VERSION_REGISTRY 와 대조해 GerritCapabilities 반환.
    레지스트리는 내림차순이므로 첫 번째 매칭이 가장 근접한 상위 버전.
    """
    for min_ver, feats in GERRIT_VERSION_REGISTRY:
        if version_tuple >= min_ver:
            caps = GerritCapabilities(
                version_str=version_str,
                version_tuple=version_tuple,
                **feats,
            )
            logger.info("Gerrit 버전 감지: %s", caps.summary())
            return caps
    # (0,0) 항목이 항상 매칭되므로 여기는 도달 불가
    return GerritCapabilities(version_str=version_str, version_tuple=version_tuple)


# ==============================================================================
# Gerrit REST API 클라이언트
# ==============================================================================

class GerritClient:
    """
    Gerrit REST API 클라이언트.

    초기화 시 버전을 자동 감지하여 GerritCapabilities 에 저장.
    이후 모든 API 호출은 capabilities 기반으로 올바른 페이로드를 구성.
    폴백(fallback) 없이 처음부터 정확한 페이로드를 전송합니다.

    새 버전 대응:
        GERRIT_VERSION_REGISTRY 에 항목 추가만으로 완료됩니다.
    수동 버전 지정:
        reviewer_config.json > gerrit.version 으로 오버라이드 가능.
    """

    MAGIC_PREFIX = ")]}'\n"

    def __init__(
        self,
        base_url:    str,
        username:    str,
        password:    str,
        auth_type:   str  = "basic",
        timeout:     int  = 30,
        verify_ssl:  bool = True,
        dry_run:     bool = False,
        version:     str  = "",     # 수동 버전 지정 (비어 있으면 자동 감지)
    ):
        self.base_url   = base_url.rstrip("/")
        self.username   = username
        self.timeout    = timeout
        self.dry_run    = dry_run
        self.verify_ssl = verify_ssl

        self.auth = (
            HTTPDigestAuth(username, password)
            if auth_type == "digest"
            else HTTPBasicAuth(username, password)
        )

        self.session = requests.Session()
        self.session.auth   = self.auth
        self.session.verify = self.verify_ssl
        self.session.headers.update({
            "Accept":       "application/json",
            "Content-Type": "application/json;charset=UTF-8",
        })

        # 버전 결정: 수동 지정 우선, 없으면 자동 감지
        if version:
            ver_tuple  = parse_version(version)
            self.caps  = detect_capabilities(ver_tuple, version)
            logger.info("버전 수동 지정 적용: %s", self.caps.summary())
        else:
            self.caps = self._detect_version()

        logger.debug(
            "GerritClient 초기화 완료: url=%s user=%s dry_run=%s caps=[%s]",
            self.base_url, self.username, self.dry_run, self.caps.summary()
        )

    # ── 버전 자동 감지 ────────────────────────────────────────────────────────

    def _detect_version(self) -> GerritCapabilities:
        """
        Gerrit 서버 버전을 조회하여 GerritCapabilities 반환.
        감지 실패 시 최소 기능 (0,0) 으로 안전하게 폴백.

        시도 순서:
          1. GET /a/config/server/version  (2.15+, 간결)
          2. GET /a/config/server/info     (구버전 호환)
        """
        raw_ver = "unknown"

        # 시도 1: /config/server/version
        try:
            resp = self.session.get(
                self._url("config/server/version"),
                timeout=self.timeout,
            )
            if resp.status_code == 200:
                text = resp.text
                if text.startswith(self.MAGIC_PREFIX):
                    text = text[len(self.MAGIC_PREFIX):]
                raw_ver = json.loads(text).strip('"')
                logger.debug("version 엔드포인트: %s", raw_ver)
        except Exception as exc:
            logger.debug("version 엔드포인트 실패(정상): %s", exc)

        # 시도 2: /config/server/info
        if raw_ver == "unknown":
            try:
                resp = self.session.get(
                    self._url("config/server/info"),
                    timeout=self.timeout,
                )
                if resp.status_code == 200:
                    text = resp.text
                    if text.startswith(self.MAGIC_PREFIX):
                        text = text[len(self.MAGIC_PREFIX):]
                    info    = json.loads(text)
                    raw_ver = (
                        info.get("gerrit", {}).get("version", "")
                        or info.get("version", "unknown")
                    )
                    logger.debug("server/info 버전: %s", raw_ver)
            except Exception as exc:
                logger.debug("server/info 실패: %s", exc)

        ver_tuple = parse_version(raw_ver)
        caps      = detect_capabilities(ver_tuple, raw_ver)

        if ver_tuple == (0, 0):
            logger.warning(
                "Gerrit 버전 자동 감지 실패 → 최소 기능 모드. "
                "reviewer_config.json 의 gerrit.version 으로 수동 지정 가능."
            )
        return caps

    def override_version(self, version_str: str) -> None:
        """버전을 수동으로 재지정합니다 (런타임 오버라이드)."""
        ver_tuple = parse_version(version_str)
        self.caps = detect_capabilities(ver_tuple, version_str)
        logger.info("버전 재지정: %s", self.caps.summary())

    # ── 내부 헬퍼 ─────────────────────────────────────────────────────────────

    def _url(self, path: str) -> str:
        return f"{self.base_url}/a/{path.lstrip('/')}"

    def _parse(self, text: str) -> dict | list:
        if text.startswith(self.MAGIC_PREFIX):
            text = text[len(self.MAGIC_PREFIX):]
        return json.loads(text)

    def _get(self, path: str, params: dict = None) -> dict | list:
        url = self._url(path)
        logger.debug("GET %s params=%s", url, params)
        resp = self.session.get(url, params=params, timeout=self.timeout)
        resp.raise_for_status()
        return self._parse(resp.text)

    def _post(self, path: str, body: dict) -> dict | list | None:
        url = self._url(path)
        if self.dry_run:
            logger.info(
                "[DRY-RUN] POST %s\n%s",
                url, json.dumps(body, indent=2, ensure_ascii=False)
            )
            return None
        logger.debug("POST %s body_keys=%s", url, list(body.keys()))
        resp = self.session.post(url, json=body, timeout=self.timeout)
        resp.raise_for_status()
        return self._parse(resp.text) if resp.text.strip() else None

    # ── 페이로드 빌더 ─────────────────────────────────────────────────────────

    def _build_review_body(self, review: ReviewInput) -> dict:
        """
        GerritCapabilities 를 기반으로 SetReviewInput 페이로드 구성.
        미지원 필드는 처음부터 제외하므로 서버 오류 없이 한 번에 성공합니다.
        """
        caps = self.caps
        body: dict = {}

        # tag (2.15+)
        if caps.tag and review.tag:
            body["tag"] = review.tag

        # message (항상)
        if review.message:
            body["message"] = review.message

        # labels (기능 지원 버전만 포함. 미지원 시 점수 없이 코멘트만 등록)
        if caps.labels and review.labels:
            body["labels"] = review.labels

        # notify (2.15+ NONE 지원. 미지원 시 OWNER/ALL만 포함)
        if caps.notify_none:
            body["notify"] = review.notify
        elif review.notify not in ("NONE",):
            body["notify"] = review.notify

        # inline comments (2.14+)
        if caps.inline_comments and review.comments:
            if caps.unresolved:
                # 3.0+: unresolved 그대로
                body["comments"] = review.comments
            else:
                # 2.14~2.x: unresolved 필드 제거
                body["comments"] = {
                    fname: [
                        {k: v for k, v in c.items() if k != "unresolved"}
                        for c in cmts
                    ]
                    for fname, cmts in review.comments.items()
                }

        logger.debug(
            "페이로드 구성 [Gerrit %s]: 필드=%s  인라인=%d개",
            caps.version_str, list(body.keys()),
            sum(len(v) for v in body.get("comments", {}).values()),
        )
        return body

    # ── 변경사항 조회 ─────────────────────────────────────────────────────────

    def get_change(self, change_number: int, patchset_number: int) -> GerritChange:
        data = self._get(
            f"changes/{change_number}",
            params={"o": ["DETAILED_ACCOUNTS", "CURRENT_REVISION"]}
        )
        owner_name = ""
        if "owner" in data:
            owner_name = data["owner"].get("name") or data["owner"].get("email", "")

        return GerritChange(
            change_id       = data.get("change_id", ""),
            project         = data.get("project", ""),
            branch          = data.get("branch", ""),
            subject         = data.get("subject", ""),
            status          = data.get("status", ""),
            change_number   = change_number,
            patchset_number = patchset_number,
            owner           = owner_name,
            created         = data.get("created", ""),
            updated         = data.get("updated", ""),
        )

    # ── Diff 조회 ─────────────────────────────────────────────────────────────

    def get_changed_files(self, change_number: int, patchset_number: int) -> list[str]:
        data = self._get(
            f"changes/{change_number}/revisions/{patchset_number}/files"
        )
        return [f for f in data.keys() if not f.startswith("/")]

    def get_file_diff(
        self,
        change_number:   int,
        patchset_number: int,
        filename:        str,
        context_lines:   int = 10,
    ) -> FileDiff:
        encoded = quote(filename, safe="")
        # intraline 은 소문자 "true" 문자열로 전달 (Python bool True → "True" 버그 방지)
        data = self._get(
            f"changes/{change_number}/revisions/{patchset_number}/files/{encoded}/diff",
            params={"context": context_lines, "intraline": "true"}
        )

        diff_lines  = []
        change_type = data.get("change_type", "MODIFIED")
        old_path    = data.get("meta_a", {}).get("name", filename)

        diff_lines.append(f"--- a/{old_path}")
        diff_lines.append(f"+++ b/{filename}")

        lines_inserted = lines_deleted = 0
        for section in data.get("content", []):
            for line in section.get("ab", []):
                diff_lines.append(f" {line}")
            for line in section.get("a", []):
                diff_lines.append(f"-{line}")
                lines_deleted += 1
            for line in section.get("b", []):
                diff_lines.append(f"+{line}")
                lines_inserted += 1

        return FileDiff(
            filename=filename, old_path=old_path, change_type=change_type,
            lines_inserted=lines_inserted, lines_deleted=lines_deleted,
            diff_content="\n".join(diff_lines),
        )

    def get_all_diffs(
        self,
        change_number:   int,
        patchset_number: int,
        max_files:       int = 50,
        context_lines:   int = 10,
    ) -> list[FileDiff]:
        files = self.get_changed_files(change_number, patchset_number)
        logger.info("변경 파일 수: %d (max_files=%d)", len(files), max_files)

        if len(files) > max_files:
            logger.warning(
                "변경 파일(%d) > max_files(%d). 처음 %d개만 처리합니다.",
                len(files), max_files, max_files
            )
            files = files[:max_files]

        diffs = []
        for fname in files:
            try:
                diff = self.get_file_diff(
                    change_number, patchset_number, fname, context_lines
                )
                diffs.append(diff)
                logger.debug("diff 획득: %s (+%d/-%d)",
                             fname, diff.lines_inserted, diff.lines_deleted)
            except Exception as exc:
                logger.warning("diff 획득 실패: %s — %s", fname, exc)
        return diffs

    # ── 리뷰 등록 ─────────────────────────────────────────────────────────────

    def post_review(
        self,
        change_number:   int,
        patchset_number: int,
        review:          ReviewInput,
    ) -> bool:
        """
        코드 리뷰 코멘트를 Gerrit에 등록합니다.

        GerritCapabilities 기반으로 페이로드를 처음부터 올바르게 구성합니다.
        5xx 오류 발생 시 labels 필드를 제거한 후 1회 재시도합니다.
        (구버전 Gerrit에서 labels 권한 문제로 500이 발생하는 경우 대응)

        Returns:
            True: 성공 (dry_run 포함), False: 실패
        """
        inline_total = sum(len(v) for v in review.comments.values()) if review.comments else 0

        if self.dry_run:
            body = self._build_review_body(review)
            logger.info(
                "[DRY-RUN] 리뷰 시뮬레이션 [%s]  인라인=%d개  label=%s  필드=%s",
                self.caps.version_str, inline_total, review.labels, list(body.keys())
            )
            return True

        if not self.caps.inline_comments and inline_total > 0:
            logger.info(
                "Gerrit %s 인라인 코멘트 미지원 → 파일별 리뷰가 Change 코멘트에 포함됩니다.",
                self.caps.version_str
            )

        body     = self._build_review_body(review)
        endpoint = f"changes/{change_number}/revisions/{patchset_number}/review"

        def _try(b: dict, stage: str) -> bool:
            """단일 POST 시도. 성공 True, 실패 False."""
            try:
                self._post(endpoint, b)
                actual_inline = sum(len(v) for v in b.get("comments", {}).values())
                logger.info(
                    "리뷰 등록 완료 [Gerrit %s / %s]: change=%d ps=%d  인라인=%d개  label=%s",
                    self.caps.version_str, stage,
                    change_number, patchset_number,
                    actual_inline, b.get("labels", "(생략)"),
                )
                return True
            except requests.HTTPError as exc:
                status    = exc.response.status_code if exc.response is not None else "?"
                body_text = exc.response.text[:300]  if exc.response is not None else ""
                logger.warning(
                    "[%s] HTTP %s: %s  응답: %s",
                    stage, status, exc, body_text
                )
                return False

        # ── 1차 시도: 버전 기반 최적 페이로드 ───────────────────────────────
        if _try(body, "FULL"):
            return True

        # ── 2차 시도: labels 제거 (5xx 권한/서버 오류 대응) ─────────────────
        if "labels" in body:
            body_no_label = {k: v for k, v in body.items() if k != "labels"}
            logger.warning(
                "labels 필드 제거 후 재시도합니다 "
                "(Gerrit %s 에서 labels 권한 문제 또는 Change 상태 오류).",
                self.caps.version_str
            )
            if _try(body_no_label, "NO-LABELS"):
                logger.warning(
                    "  Code-Review 점수(%s)는 등록되지 않았습니다. "
                    "Gerrit 에서 ai-reviewer 계정의 Label 권한을 확인하세요.",
                    review.labels
                )
                return True

        # ── 최종 실패 ────────────────────────────────────────────────────────
        logger.error(
            "리뷰 등록 최종 실패 [Gerrit %s] (change=%d ps=%d).",
            self.caps.version_str, change_number, patchset_number
        )
        logger.error(
            "  버전 감지 결과: %s  — 실제 버전과 다를 경우 "
            "reviewer_config.json 에 gerrit.version 을 수동 지정하세요.",
            self.caps.summary()
        )
        return False

    # ── 연결 테스트 ───────────────────────────────────────────────────────────

    def test_connection(self) -> bool:
        try:
            data    = self._get("config/server/info")
            project = data.get("gerrit", {}).get("all_projects_name", "All-Projects")
            logger.info(
                "Gerrit 연결 성공: %s  all_projects=%s  %s",
                self.base_url, project, self.caps.summary()
            )
            return True
        except Exception as exc:
            logger.error("Gerrit 연결 실패: %s — %s", self.base_url, exc)
            return False
