"""
base_ai.py
----------
모든 AI 제공자가 상속받는 추상 베이스 클래스.
"""

import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal, Optional

OutputFormat = Literal["text", "markdown"]

logger = logging.getLogger(__name__)

# ── 재시도 기본값 ────────────────────────────────────────
DEFAULT_RETRY_COUNT = 3      # 최대 재시도 횟수 (최초 1회 + 재시도 N회)
DEFAULT_RETRY_DELAY = 5.0    # 첫 번째 재시도 대기(초) — 이후 2배씩 증가


@dataclass
class SearchSource:
    """웹 검색 출처 정보"""
    title: str = ""
    url:   str = ""

    def __str__(self) -> str:
        if self.url:
            return f"{self.title}  ({self.url})" if self.title else self.url
        return self.title


@dataclass
class ChatResponse:
    """AI 응답 결과를 담는 데이터 클래스"""
    prompt:           str
    answer:           str
    model:            str
    provider:         str
    is_dry_run:       bool                = False
    timestamp:        datetime            = field(default_factory=datetime.now)
    tokens_used:      Optional[int]       = None
    elapsed_seconds:  Optional[float]     = None
    error:            Optional[str]       = None
    # ── 웹 검색 관련 ──────────────────────────────
    web_search_used:  bool                = False
    search_sources:   list[SearchSource]  = field(default_factory=list)

    @property
    def success(self) -> bool:
        return self.error is None

    # ── 일반 텍스트 포맷 (기본) ────────────────────
    def to_text(self) -> str:
        sep  = "=" * 60
        thin = "-" * 60
        dry_label    = " [Dry Run]"    if self.is_dry_run    else ""
        search_label = " [웹검색 사용]" if self.web_search_used else ""

        meta_lines = [
            f"  AI 제공자 : {self.provider}",
            f"  모델      : {self.model}",
            f"  생성 시각 : {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}{dry_label}{search_label}",
        ]
        if self.tokens_used:
            meta_lines.append(f"  사용 토큰 : {self.tokens_used}")
        if self.elapsed_seconds:
            meta_lines.append(f"  응답 시간 : {self.elapsed_seconds:.2f}초")

        body = (
            f"{sep}\n"
            + "\n".join(meta_lines) + "\n"
            + f"{thin}\n"
            f"[AI 검토 답변]\n"
            f"{self.answer}\n"
        )

        if self.web_search_used and self.search_sources:
            body += f"{thin}\n[참고 출처]\n"
            for i, src in enumerate(self.search_sources, 1):
                body += f"  [{i}] {src}\n"

        body += (
            f"{sep}\n"
            f"Generated by AI Chat CLI -- {self.timestamp.strftime('%Y-%m-%d')}\n"
        )
        return body

    # ── 마크다운 포맷 ──────────────────────────────
    def to_markdown(self) -> str:
        dry_badge     = " *(Dry Run)*"    if self.is_dry_run    else ""
        search_badge  = " 🔍 *(웹검색)*"  if self.web_search_used else ""
        token_info    = f"| 사용 토큰 | `{self.tokens_used}` |\n"          if self.tokens_used    else ""
        elapsed_info  = f"| 응답 시간 | `{self.elapsed_seconds:.2f}초` |\n" if self.elapsed_seconds else ""
        search_info   = f"| 웹 검색 | `사용` |\n"                           if self.web_search_used else ""

        sources_section = ""
        if self.web_search_used and self.search_sources:
            src_lines = "\n".join(
                f"| {i} | [{src.title or src.url}]({src.url}) |"
                for i, src in enumerate(self.search_sources, 1)
                if src.url
            )
            if src_lines:
                sources_section = (
                    "\n---\n\n## 🔗 참고 출처\n\n"
                    "| # | 출처 |\n"
                    "|---|------|\n"
                    f"{src_lines}\n"
                )

        return (
            f"# AI 채팅 응답{dry_badge}{search_badge}\n\n"
            f"## 📋 메타 정보\n\n"
            f"| 항목 | 값 |\n"
            f"|------|-----|\n"
            f"| AI 제공자 | `{self.provider}` |\n"
            f"| 모델 | `{self.model}` |\n"
            f"| 생성 시각 | `{self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}` |\n"
            f"{token_info}{elapsed_info}{search_info}"
            f"---\n\n"
            f"## 💬 AI 답변\n\n"
            f"{self.answer}\n"
            f"{sources_section}\n"
            f"---\n"
            f"*Generated by AI Chat CLI — {self.timestamp.strftime('%Y-%m-%d')}*\n"
        )

    def to_format(self, fmt: OutputFormat = "text") -> str:
        if fmt == "markdown":
            return self.to_markdown()
        return self.to_text()


class BaseAI(ABC):
    """모든 AI 제공자의 추상 베이스 클래스."""

    def __init__(
        self,
        api_key:     str,
        model:       Optional[str] = None,
        dry_run:     bool  = False,
        web_search:  bool  = False,
        retry_count: int   = DEFAULT_RETRY_COUNT,
        retry_delay: float = DEFAULT_RETRY_DELAY,
    ):
        """
        Args:
            api_key:     AI 서비스 API 키
            model:       사용할 모델명 (None이면 default_model 사용)
            dry_run:     True이면 실제 API 호출 없이 테스트 응답 반환
            web_search:  True이면 실시간 웹 검색 도구 활성화
            retry_count: 일시적 오류 발생 시 최대 재시도 횟수 (기본 3)
            retry_delay: 첫 재시도 대기 시간(초), 이후 2배씩 증가 (기본 5초)
        """
        self.api_key     = api_key
        self.model       = model or self.default_model
        self.dry_run     = dry_run
        self.web_search  = web_search
        self.retry_count = retry_count
        self.retry_delay = retry_delay

    @property
    @abstractmethod
    def provider_name(self) -> str: ...

    @property
    @abstractmethod
    def default_model(self) -> str: ...

    @abstractmethod
    def _call_api(self, prompt: str) -> ChatResponse: ...

    def _is_retryable_error(self, error_msg: str) -> bool:
        """
        재시도 가능한 일시적 오류인지 판별합니다.
        각 AI 구현체에서 오버라이드 가능합니다.

        재시도 대상:
          - 503 Service Unavailable (모델 과부하)
          - 429 Too Many Requests   (속도 제한)
          - 500 Internal Server Error
          - 502 Bad Gateway
          - 504 Gateway Timeout
          - UNAVAILABLE / RESOURCE_EXHAUSTED (gRPC 코드)
        """
        RETRYABLE_PATTERNS = [
            "503", "429", "500", "502", "504",
            "UNAVAILABLE", "RESOURCE_EXHAUSTED",
            "rate_limit", "rate limit",
            "Service Unavailable", "temporarily unavailable",
            "high demand", "overloaded", "try again",
            "timeout", "Timeout",
        ]
        em = error_msg.lower()
        return any(p.lower() in em for p in RETRYABLE_PATTERNS)

    def _dry_run_response(self, prompt: str) -> ChatResponse:
        """API 호출 없이 테스트용 응답을 생성합니다."""
        search_note = "\n웹 검색 : 활성화 (dry run 이므로 실제 검색 미수행)" if self.web_search else ""
        answer = (
            "[Dry Run 테스트 응답]\n\n"
            "이것은 실제 API 호출 없이 생성된 테스트 응답입니다.\n\n"
            f"입력된 프롬프트:\n  {prompt}\n\n"
            f"Provider : {self.provider_name}\n"
            f"Model    : {self.model}\n"
            f"Mode     : Dry Run (테스트 모드)"
            f"{search_note}\n\n"
            "실제 응답을 받으려면 --dry-run 옵션을 제거하세요."
        )
        return ChatResponse(
            prompt=prompt,
            answer=answer,
            model=self.model,
            provider=self.provider_name,
            is_dry_run=True,
        )

    def chat(self, prompt: str) -> ChatResponse:
        """
        프롬프트를 전송하고 응답을 받습니다.
        일시적 오류 발생 시 지수 백오프로 자동 재시도합니다.

        재시도 간격: retry_delay → retry_delay*2 → retry_delay*4 → …
        """
        if self.dry_run:
            return self._dry_run_response(prompt)

        last_response: Optional[ChatResponse] = None
        delay = self.retry_delay

        for attempt in range(1, self.retry_count + 2):  # 1회 + 최대 retry_count회
            response = self._call_api(prompt)

            # ── 성공 ─────────────────────────────────────────
            if response.success:
                if attempt > 1:
                    logger.info(
                        "✅ %s 재시도 성공 (시도 %d/%d)",
                        self.provider_name, attempt, self.retry_count + 1
                    )
                return response

            last_response = response

            # ── 재시도 가능 여부 판별 ─────────────────────────
            is_last_attempt = (attempt == self.retry_count + 1)
            if is_last_attempt or not self._is_retryable_error(response.error or ""):
                break   # 재시도 불가 오류이거나 횟수 소진

            # ── 재시도 대기 ───────────────────────────────────
            logger.warning(
                "⚠️  %s API 일시 오류 (시도 %d/%d) — %.0f초 후 재시도합니다.\n"
                "    오류: %s",
                self.provider_name, attempt, self.retry_count + 1,
                delay,
                (response.error or "")[:120],
            )
            time.sleep(delay)
            delay *= 2  # 지수 백오프

        return last_response  # type: ignore
